DROP TABLE IF EXISTS video;
CREATE TABLE video (
  vID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  winner INTEGER,
  loser INTEGER,
  url TEXT,
  tournament TEXT,
  year INTEGER,
  FOREIGN KEY(winner) REFERENCES player(pID),
  FOREIGN KEY(loser) REFERENCES player(pID)
);

DROP TABLE IF EXISTS game;
CREATE TABLE game (
  gID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  vID INTEGER,
  winner INTEGER,
  loser INTEGER,
  stage INTEGER,
  match INTEGER,
  FOREIGN KEY(vID) REFERENCES video(vID),
  FOREIGN KEY(winner) REFERENCES player(pID),
  FOREIGN KEY(loser) REFERENCES player(pID),
  FOREIGN KEY(stage) REFERENCES stage(sID)
);

DROP TABLE IF EXISTS player;
CREATE TABLE player (
  pID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name TEXT
);

DROP TABLE IF EXISTS character;
CREATE TABLE character (
  cID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name TEXT
);

DROP TABLE IF EXISTS stage;
CREATE TABLE stage (
  sID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name TEXT
);

DROP TABLE IF EXISTS playerGameCharacter;
CREATE TABLE playerGameCharacter (
  game INTEGER,
  player INTEGER,
  character INTEGER,
  FOREIGN KEY(game) REFERENCES game(gID),
  FOREIGN KEY(player) REFERENCES player(pID),
  FOREIGN KEY(character) REFERENCES character(cID),
  PRIMARY KEY (game, player, character)
);