DROP TABLE IF EXISTS video;
CREATE TABLE video (
  vID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  winner INTEGER FOREIGN KEY REFERENCES player,
  loser INTEGER FOREIGN KEY REFERENCES player,
  url STRING,
  tournament STRING,
  year INTEGER
);

DROP TABLE IF EXISTS game;
CREATE TABLE game (
  gID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  vID INTEGER FOREIGN KEY REFERENCES video,
  winner INTEGER FOREIGN KEY REFERENCES player,
  loser INTEGER FOREIGN KEY REFERENCES player,
  stage INTEGER FOREIGN KEY REFERENCES stage,
  match INTEGER
);

DROP TABLE IF EXISTS player;
CREATE TABLE player (
  pID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name STRING
);

DROP TABLE IF EXISTS character;
CREATE TABLE character (
  cID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name STRING
);

DROP TABLE IF EXISTS stage;
CREATE TABLE stage (
  sID INTEGER PRIMARY KEY UNIQUE NOT NULL,
  name STRING
);